<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>CH4</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="site_libs/datatables-binding-0.34.0/datatables.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">期末報告</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="ch1.html">CH1 緒論</a>
</li>
<li>
  <a href="ch2.html">CH2 文獻回顧</a>
</li>
<li>
  <a href="ch3.html">CH3 研究方法</a>
</li>
<li>
  <a href="ch4.html">CH4 研究結果</a>
</li>
<li>
  <a href="ch5.html">CH5 資料生成邏輯與原始數據</a>
</li>
<li>
  <a href="reference.html">附註與參考文獻</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">CH4</h1>

</div>


<div id="資料來源" class="section level2">
<h2>4.1 資料來源</h2>
<p>於本次所採用的原始數據細節，以及各項投入與產出在實務上之具體定義，詳見
第ch5：資料生成邏輯與原始數據。
資料庫涵蓋了車輛派遣時間、行駛里程、志工與學生投入工時、以及每趟車次之補貼油資。</p>
</div>
<div id="資料處理" class="section level2">
<h2>4.2 資料處理</h2>
<p>為落實社會轉變理論之架構，並確保指標選取運算之邏輯一致性，建立如表
4-1
所示之指標對照體系。該表將偏鄉共乘服務之營運與社會效益，拆解為三個階段之投入與產出變數：</p>
<table class="table table-striped table-hover table-condensed" style="margin-left: auto; margin-right: auto;">
<caption>
表 4-1：偏鄉共乘服務之 Network DEA 指標體系與社會轉變理論對照表
</caption>
<thead>
<tr>
<th style="text-align:left;">
Phase
</th>
<th style="text-align:left;">
Role
</th>
<th style="text-align:left;">
Symbol
</th>
<th style="text-align:left;">
Name
</th>
<th style="text-align:left;">
Logic
</th>
<th style="text-align:left;">
ToC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
第一階段 (營運)
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
原始投入
</td>
<td style="text-align:left;">
<span><span class="math inline">\(x_{1}^1\)</span></span>
</td>
<td style="text-align:left;">
志工時間
</td>
<td style="text-align:left;">
實際總投入工時
</td>
<td style="text-align:left;">
利害關係人投入
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(x_{2}^1\)</span></span>
</td>
<td style="text-align:left;">
補貼與油資
</td>
<td style="text-align:left;">
里程*5+補貼額
</td>
<td style="text-align:left;">
USR 經費配置
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(x_{3}^1\)</span></span>
</td>
<td style="text-align:left;">
學生時間
</td>
<td style="text-align:left;">
實際調度工時
</td>
<td style="text-align:left;">
人力成本
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
中間產出
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
服務產出
</td>
<td style="text-align:left;">
<span><span class="math inline">\(z_{1}^{12}\)</span></span>
</td>
<td style="text-align:left;">
準時程度
</td>
<td style="text-align:left;">
1/(1 + |預約差值|)
</td>
<td style="text-align:left;">
運輸品質
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(z_{2}^{12}\)</span></span>
</td>
<td style="text-align:left;">
有效人公里
</td>
<td style="text-align:left;">
距離 x 搭乘人數
</td>
<td style="text-align:left;">
實質服務供給
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(z_{3}^{12}\)</span></span>
</td>
<td style="text-align:left;">
服務覆蓋度
</td>
<td style="text-align:left;">
1-大眾運輸可達里程/總里程
</td>
<td style="text-align:left;">
可及範圍
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="4">
第二階段 (社會)
</td>
<td style="text-align:left;">
額外投入
</td>
<td style="text-align:left;">
<span><span class="math inline">\(x_{1}^2\)</span></span>
</td>
<td style="text-align:left;">
學生轉換時間
</td>
<td style="text-align:left;">
實際投入工時
</td>
<td style="text-align:left;">
增加社會資本
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="3">
最終產出
</td>
<td style="text-align:left;">
<span><span class="math inline">\(y_{1}^2\)</span></span>
</td>
<td style="text-align:left;">
時間費用節散
</td>
<td style="text-align:left;">
時間*196+實際節省交通費
</td>
<td style="text-align:left;">
降低交通負擔
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(y_{2}^{2}\)</span></span>
</td>
<td style="text-align:left;">
減碳量價值
</td>
<td style="text-align:left;">
碳排差額 x 碳價
</td>
<td style="text-align:left;">
環境效益
</td>
</tr>
<tr>
<td style="text-align:left;">
<span><span class="math inline">\(y_{3}^2\)</span></span>
</td>
<td style="text-align:left;">
參與收穫價值
</td>
<td style="text-align:left;">
問卷計算
</td>
<td style="text-align:left;">
社交連結
</td>
</tr>
</tbody>
</table>
</div>
<div id="資料分析" class="section level2">
<h2>4.3 資料分析</h2>
<p>針對偏鄉共乘服務的各階段效率進行統計，結果如表 4-2
所示。整體樣本之營運效率平均值為0.749，標準差為0.205；社福效率平均值為
0.753，標準差為0.236，整體效率平均為0.725</p>
<pre class="r"><code>library(dplyr)
library(knitr)
library(kableExtra)
library(readxl)

QQ &lt;- read_excel(&quot;C:/Users/x2991/Downloads/QQ.xlsx&quot;)

# 1. 計算各組數據
group_stats &lt;- QQ %&gt;%
  group_by(purpose) %&gt;%
  summarise(
    樣本數 = n(),
    營運平均 = round(mean(S1E, na.rm = TRUE), 3),
    營運SD = round(sd(S1E, na.rm = TRUE), 3),
    社福平均 = round(mean(S2E, na.rm = TRUE), 3),
    社福SD = round(sd(S2E, na.rm = TRUE), 3),
    綜合平均 = round(mean(FE, na.rm = TRUE), 3)
  )

# 2. 計算全體樣本數據 (Overall)
overall_stats &lt;- QQ %&gt;%
  summarise(
    purpose = &quot;全體樣本&quot;,
    樣本數 = n(),
    營運平均 = round(mean(S1E, na.rm = TRUE), 3),
    營運SD = round(sd(S1E, na.rm = TRUE), 3),
    社福平均 = round(mean(S2E, na.rm = TRUE), 3),
    社福SD = round(sd(S2E, na.rm = TRUE), 3),
    綜合平均 = round(mean(FE, na.rm = TRUE), 3)
  )

# 3. 合併表格
final_table &lt;- bind_rows(group_stats, overall_stats)

# 4. 輸出最終版表格
kable(final_table, 
      &quot;html&quot;, 
      caption = &quot;表 4-2：各目的別與全體樣本投入與產出效率之描述性統計&quot;,
      col.names = c(&quot;搭乘目的&quot;, &quot;樣本數&quot;, &quot;營運(平均)&quot;, &quot;營運(SD)&quot;, &quot;社福(平均)&quot;, &quot;社福(SD)&quot;, &quot;綜合(平均)&quot;)) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;), full_width = FALSE) %&gt;%
  # 最後一行（總計）加粗，看起來更醒目
  row_spec(nrow(final_table), bold = TRUE, background = &quot;#f2f2f2&quot;)</code></pre>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
表 4-2：各目的別與全體樣本投入與產出效率之描述性統計
</caption>
<thead>
<tr>
<th style="text-align:left;">
搭乘目的
</th>
<th style="text-align:right;">
樣本數
</th>
<th style="text-align:right;">
營運(平均)
</th>
<th style="text-align:right;">
營運(SD)
</th>
<th style="text-align:right;">
社福(平均)
</th>
<th style="text-align:right;">
社福(SD)
</th>
<th style="text-align:right;">
綜合(平均)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
USR活動
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.908
</td>
<td style="text-align:right;">
0.123
</td>
<td style="text-align:right;">
0.856
</td>
<td style="text-align:right;">
0.185
</td>
<td style="text-align:right;">
0.870
</td>
</tr>
<tr>
<td style="text-align:left;">
就學
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.943
</td>
<td style="text-align:right;">
0.080
</td>
<td style="text-align:right;">
0.848
</td>
<td style="text-align:right;">
0.178
</td>
<td style="text-align:right;">
0.875
</td>
</tr>
<tr>
<td style="text-align:left;">
就醫
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.523
</td>
<td style="text-align:right;">
0.114
</td>
<td style="text-align:right;">
0.851
</td>
<td style="text-align:right;">
0.199
</td>
<td style="text-align:right;">
0.666
</td>
</tr>
<tr>
<td style="text-align:left;">
觀光
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.753
</td>
<td style="text-align:right;">
0.162
</td>
<td style="text-align:right;">
0.751
</td>
<td style="text-align:right;">
0.175
</td>
<td style="text-align:right;">
0.729
</td>
</tr>
<tr>
<td style="text-align:left;">
購物
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
0.621
</td>
<td style="text-align:right;">
0.144
</td>
<td style="text-align:right;">
0.459
</td>
<td style="text-align:right;">
0.178
</td>
<td style="text-align:right;">
0.484
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
全體樣本
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
0.749
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
0.205
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
0.753
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
0.236
</td>
<td style="text-align:right;font-weight: bold;background-color: rgba(242, 242, 242, 255) !important;">
0.725
</td>
</tr>
</tbody>
</table>
<div class="datatables html-widget html-fill-item" id="htmlwidget-9c65be7bc8b853bdc9a0" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-9c65be7bc8b853bdc9a0">{"x":{"filter":"none","vertical":false,"caption":"<caption>表 4-3：兩階段 Network DEA 效率數據<\/caption>","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100],["就學1","就學2","就學3","就學4","就學5","就學6","就學7","就學8","就學9","就學10","就學11","就學12","就學13","就學14","就學15","就學16","就學17","就學18","就學19","就學20","購物1","購物2","購物3","購物4","購物5","購物6","購物7","購物8","購物9","購物10","購物11","購物12","購物13","購物14","購物15","購物16","購物17","購物18","購物19","購物20","就醫1","就醫2","就醫3","就醫4","就醫5","就醫6","就醫7","就醫8","就醫9","就醫10","就醫11","就醫12","就醫13","就醫14","就醫15","就醫16","就醫17","就醫18","就醫19","就醫20","觀光1","觀光2","觀光3","觀光4","觀光5","觀光6","觀光7","觀光8","觀光9","觀光10","觀光11","觀光12","觀光13","觀光14","觀光15","觀光16","觀光17","觀光18","觀光19","觀光20","USR1","USR2","USR3","USR4","USR5","USR6","USR7","USR8","USR9","USR10","USR11","USR12","USR13","USR14","USR15","USR16","USR17","USR18","USR19","USR20"],["就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","就學","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","購物","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","就醫","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","觀光","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動","USR活動"],[1,0.9993,1,0.9994,1,0.7907,0.8188,0.9708,0.9236,1,0.9611,1,0.9153,1,0.8158,0.8736,1,1,1,0.7897999999999999,0.5778,0.5669999999999999,0.472,0.6496,0.665,0.7527,0.6242,0.7864,0.736,0.5634,0.5764,0.4662,0.4184,0.4562,0.7015,0.5199,1,0.8110000000000001,0.5629,0.5175999999999999,0.4981,0.3841,0.5631,0.4235,0.4478,0.4622,0.5917,0.4139,0.5608,0.555,0.513,0.5592,0.48,0.7895,0.5677,0.6207,0.4544,0.4447,0.3533,0.7741,0.9399,0.7358,0.4844,0.6619,0.4472,1,0.5452,0.6830000000000001,0.7766,0.8621,0.7926,0.7695,0.8231000000000001,0.832,0.9995000000000001,0.6022,0.6656,0.7096,0.7257,1,0.9952,0.8814,0.9029,0.9998,0.7161999999999999,0.6849,0.7863,0.9837,1,0.9999,1,0.9997,1,0.8796,1,0.6074000000000001,0.8767,0.8381,1,0.9999],[1,0.994,1,0.65,1,0.72,0.7462,0.9883999999999999,0.5865,0.9997,0.6969,1,0.5977,1,0.5786,0.6041,1,1,1,0.7977,0.5581,0.4976,0.5232,0.3439,0.3911,0.35,0.3985,0.3316,0.2954,0.4197,0.5994,0.463,0.4771,0.5681,0.2149,0.2732,1,0.3687,0.368,0.73,1,0.8305,0.8017,0.7112000000000001,0.8243,0.8394,0.6824,0.9415,1,1,1,0.7679,0.8987000000000001,1,0.8703,0.1497,0.9952,0.7165,0.996,1,0.8474,0.4723,0.7822,0.6543,0.6936,1,0.6424,0.5876,0.9124,0.8671,0.6123,0.7946,0.5849,0.8211000000000001,1,0.7010999999999999,0.9964,0.5843,0.4748,1,0.9961,0.8088,0.9319,0.9985000000000001,0.3945,0.7931,0.6242,0.7836,1,0.9999,1,0.9999,1,0.8449,0.9998,0.6524,0.5157,0.784,1,1],[1,0.996,1,0.7653,1,0.723,0.761,0.9794,0.7043,0.9998,0.793,1,0.6908,1,0.6543,0.6954,1,1,1,0.7448,0.5448,0.5105,0.4799,0.4196,0.4507,0.4446,0.4399,0.4541,0.398,0.4517,0.5482,0.4521,0.4435,0.5142,0.2993,0.3149,1,0.4851,0.4136,0.6232,0.749,0.5639999999999999,0.6767,0.5379,0.6097,0.6349,0.6205000000000001,0.6567,0.7804,0.7773,0.7565,0.663,0.6677,0.8947000000000001,0.6998,0.2082,0.7235,0.5702,0.6348,0.8869,0.8694,0.5517,0.6328,0.6349,0.5588,1,0.5715,0.6146,0.8184,0.8453000000000001,0.6677,0.7543,0.6613,0.7675,0.9998,0.6337,0.8307,0.6234,0.5407999999999999,1,0.9927,0.8273,0.9141,0.9989,0.4805,0.7336,0.6757,0.8621,1,0.9999,1,0.9997,1,0.8563,0.9998,0.6218,0.6359,0.7919,1,0.9999]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>No.<\/th>\n      <th>DMU<\/th>\n      <th>搭乘目的<\/th>\n      <th>營運效率<\/th>\n      <th>社會轉化效率<\/th>\n      <th>最終效率<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"scrollX":true,"autoWidth":true,"columnDefs":[{"className":"dt-center","targets":"_all"},{"width":"150px","targets":"_all"},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"No.","targets":1},{"name":"DMU","targets":2},{"name":"purpose","targets":3},{"name":"S1E","targets":4},{"name":"S2E","targets":5},{"name":"FE","targets":6}],"language":{"search":"搜尋 DEA 指標 / DMU：","lengthMenu":"效率數據每頁顯示 _MENU_ 筆"},"order":[],"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>圖 4-1 至 4-3 之分析：偏鄉共乘的效率與轉化機制
「本研究透過三階段箱形圖分析，探討偏鄉共乘系統在不同搭乘目的下，從『營運投入』到『社會價值產出』之轉化過程：</p>
<p>營運端的資源穩定性（圖
4-1）：『就學』與『USR活動』在第一階段展現出極高的營運效率中位數（趨近
1.0），此類具有固定時程、預期乘客數穩定之目的別，較能發揮運輸資源調度。</p>
<p>社會價值傳換的效率（圖
4-2）：『就醫』需求在營運階段雖效率受限，但在第二階段社會效益轉換中，展現出較高的效率。此現象證實在面對社會價值轉換導向需求時，具有將低營運效率轉化為高社會價值（如：提升長者就醫可及性）的補償機制。</p>
<p>最終效率的結構（圖
4-3）：綜合兩階段之最終效率顯示，各目的別之績效分佈呈現顯著的結構性差異。其中，就學與USR活動持續位居效率頂端；就醫透過社會價值轉換的效率，在最終績效上向上成長，由原本的低效群體提升至中段水準；而『購物』與『觀光』類別，在營運與社福兩階段均沒有有效轉化，最終績效呈現落後。</p>
<p><img src="ch4_files/figure-html/unnamed-chunk-4-1.png" alt="" width="672" /><img src="ch4_files/figure-html/unnamed-chunk-4-2.png" alt="" width="672" /><img src="ch4_files/figure-html/unnamed-chunk-4-3.png" alt="" width="672" /></p>
</div>
<div id="假設檢定與無母數分析" class="section level2">
<h2>4.4 假設檢定與無母數分析</h2>
<p>為探討不同搭乘目的（就學、購物、就醫、觀光、USR
活動）對於偏鄉共乘服務效率之影響，本研究依據統計分析之嚴謹程序，執行以下檢定步驟：</p>
<p>常態性檢定：首先以 Shapiro-Wilk Test
檢定各階段效率指標之分布情形。檢定結果顯示，各項指標之 <span
class="math inline">\(p\)</span>-value 均小於
0.05，故判定數據不符合常態分配假設，不適合ANOVA。</p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  QQ$S1E
## W = 0.90489, p-value = 2.42e-06</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  S1E by purpose
## Kruskal-Wallis chi-squared = 60.384, df = 4, p-value = 2.408e-12</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  S2E by purpose
## Kruskal-Wallis chi-squared = 36.069, df = 4, p-value = 2.801e-07</code></pre>
<p>組間差異檢定：基於數據非常態特性，本研究採用無母數分析中之
Kruskal-Wallis
Test，以檢定五種搭乘目的組別間之效率中位數是否存在顯著差異。</p>
<p>事後多重比較：若 Kruskal-Wallis Test 之 <span
class="math inline">\(p\)</span>-value 達顯著水準，則進一步採用 Pairwise
Wilcoxon Test（並結合 BH 方法進行 <span
class="math inline">\(p\)</span>-value
校正），以確定兩兩目的別間之效率差異來源。」</p>
<p>檢定 A:第一階段</p>
<p>H0:五種搭乘目的的第一階段效率中位數皆無顯著差異。</p>
<p>H1:五種搭乘目的之第一階段效率中位數至少有兩組具顯著差異。</p>
<p>檢定 B:第二階段</p>
<p>H0:五種搭乘目的之第二階段效率中位數皆無顯著差異。</p>
<p>H1:五種搭乘目的之第二階段效率中位數至少有兩組具顯著差異。</p>
<p>檢定 C:最終效率</p>
<p>H0:五種搭乘目的之最終效率中位數皆無顯著差異。</p>
<p>H1:五種搭乘目的之最終效率中位數至少有兩組具顯著差異。</p>
<pre class="r"><code>QQ$grp_chinese &lt;- factor(QQ$purpose, levels = c(&quot;就學&quot;, &quot;購物&quot;, &quot;就醫&quot;, &quot;觀光&quot;, &quot;USR活動&quot;))

# 檢定A第一階段效率

cat(&quot;檢定 A:第一階段效率整體與事後兩兩檢定\n&quot;)</code></pre>
<pre><code>檢定 A:第一階段效率整體與事後兩兩檢定</code></pre>
<pre class="r"><code>cat(&quot;整體檢定(Kruskal-Wallis Test)：\n&quot;)</code></pre>
<pre><code>整體檢定(Kruskal-Wallis Test)：</code></pre>
<pre class="r"><code>kw_S1E &lt;- kruskal.test(S1E ~ grp_chinese, data = QQ)
print(kw_S1E)</code></pre>
<pre><code>
    Kruskal-Wallis rank sum test

data:  S1E by grp_chinese
Kruskal-Wallis chi-squared = 60.384, df = 4, p-value = 2.408e-12</code></pre>
<pre class="r"><code># 2. 兩兩比較表格 換成 Pairwise Wilcoxon 矩陣
cat(&quot;第一階段效率兩兩比較(Pairwise Wilcoxon)\n&quot;)</code></pre>
<pre><code>第一階段效率兩兩比較(Pairwise Wilcoxon)</code></pre>
<pre class="r"><code>pw_S1E &lt;- pairwise.wilcox.test(QQ$S1E, QQ$grp_chinese, p.adjust.method = &quot;BH&quot;)
print(pw_S1E)</code></pre>
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  QQ$S1E and QQ$grp_chinese 

        就學    購物    就醫    觀光   
購物    5.7e-08 -       -       -      
就醫    1.5e-10 0.01466 -       -      
觀光    0.00015 0.01288 4.9e-05 -      
USR活動 0.26787 4.1e-06 4.9e-09 0.00329

P value adjustment method: BH </code></pre>
<pre class="r"><code># 檢定B第二階段效率

cat(&quot;檢定 B:第二階段效率整體與事後兩兩檢定\n&quot;)</code></pre>
<pre><code>檢定 B:第二階段效率整體與事後兩兩檢定</code></pre>
<pre class="r"><code>cat(&quot;整體檢定(Kruskal-Wallis Test)\n&quot;)</code></pre>
<pre><code>整體檢定(Kruskal-Wallis Test)</code></pre>
<pre class="r"><code>kw_S2E &lt;- kruskal.test(S2E ~ grp_chinese, data = QQ)
print(kw_S2E)</code></pre>
<pre><code>
    Kruskal-Wallis rank sum test

data:  S2E by grp_chinese
Kruskal-Wallis chi-squared = 36.069, df = 4, p-value = 2.801e-07</code></pre>
<pre class="r"><code>cat(&quot;第二階段效率兩兩比較(Pairwise Wilcoxon)\n&quot;)</code></pre>
<pre><code>第二階段效率兩兩比較(Pairwise Wilcoxon)</code></pre>
<pre class="r"><code>pw_S2E &lt;- pairwise.wilcox.test(QQ$S2E, QQ$grp_chinese, p.adjust.method = &quot;BH&quot;)
print(pw_S2E)</code></pre>
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  QQ$S2E and QQ$grp_chinese 

        就學    購物    就醫  觀光 
購物    1.6e-06 -       -     -    
就醫    1.000   7.8e-06 -     -    
觀光    0.141   1.2e-05 0.068 -    
USR活動 1.000   4.6e-06 1.000 0.127

P value adjustment method: BH </code></pre>
<pre class="r"><code>cat(&quot;檢定C最終效率整體與事後兩兩檢定\n&quot;)</code></pre>
<pre><code>檢定C最終效率整體與事後兩兩檢定</code></pre>
<pre class="r"><code># 1. 整體檢定 (拒絕 H0)
cat(&quot;整體檢定( Kruskal-Wallis Test) \n&quot;)</code></pre>
<pre><code>整體檢定( Kruskal-Wallis Test) </code></pre>
<pre class="r"><code>kw_FE &lt;- kruskal.test(FE ~ grp_chinese, data = QQ)
print(kw_FE)</code></pre>
<pre><code>
    Kruskal-Wallis rank sum test

data:  FE by grp_chinese
Kruskal-Wallis chi-squared = 50.057, df = 4, p-value = 3.513e-10</code></pre>
<pre class="r"><code># 2. 事後兩兩比較表格
cat(&quot;最終效率兩兩比較(Pairwise Wilcoxon)\n&quot;)</code></pre>
<pre><code>最終效率兩兩比較(Pairwise Wilcoxon)</code></pre>
<pre class="r"><code>pw_FE &lt;- pairwise.wilcox.test(QQ$FE, QQ$grp_chinese, p.adjust.method = &quot;BH&quot;)
print(pw_FE)</code></pre>
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum exact test 

data:  QQ$FE and QQ$grp_chinese 

        就學    購物    就醫    觀光   
購物    1.3e-07 -       -       -      
就醫    9.7e-05 2.0e-05 -       -      
觀光    0.00509 5.6e-07 0.61052 -      
USR活動 0.61052 5.6e-07 0.00033 0.01356

P value adjustment method: BH </code></pre>
<div id="finding-1" class="section level3">
<h3>Finding 1</h3>
<div id="第一階段" class="section level4">
<h4>第一階段</h4>
<p>第一階段為營運效率，整體 Kruskal-Wallis 檢定呈現高度顯著(<span
class="math inline">\(\chi^2\)</span>=60.384,p &lt;
0.001)，拒絕五組中位數無顯著差異的虛無假設</p>
<p>兩兩比較中發現USR活動-就學的p-value為0.268（無顯著差異）</p>
<p>數據表示，就學與USR活動兩組在第一階段營運效率的分布上具有一定程度的同質性</p>
<p>進一步交叉比對發現，就學與USR活動兩組，在面對其他目的別（購物、就醫、觀光）時，其兩兩比較的p-value均達到極度顯著之統計水準p&lt;0.01。</p>
<p>因此在顯著水準 <span class="math inline">\(\alpha\)</span> =
0.05下，就學與USR活動在第一階段效率表現明顯優於其他目的。</p>
</div>
<div id="第二階段" class="section level4">
<h4>第二階段</h4>
<p>第二階段為社會轉換效率，整體 Kruskal-Wallis
檢定結果呈現高度顯著（<span class="math inline">\(\chi^2 =
36.069\)</span>，<span class="math inline">\(p &lt;
0.001\)</span>），拒絕五組效率中位數無顯著差異之虛無假設。</p>
<p>比較中發現USR活動、就學、就醫任兩個的p-value皆達到完全不顯著(p=1)</p>
<p>在顯著水準 <span class="math inline">\(\alpha\)</span> = 0.001 至
0.05 的範圍內都無法拒絕此三組兩兩互比之虛無假設</p>
<p>因此判定
就醫、就學與USR活動三組在第二階段社會轉換效率的分布上，具備極高的統計同質性，在社會轉換效率上高度相同</p>
<p>而購物在跟其他目的比較時都呈現高度顯著(p&lt;0.001)，因此判定購物在社會轉換效率明顯低於其他目的。</p>
</div>
<div id="最終效率" class="section level4">
<h4>最終效率</h4>
<p>最終效率整體 Kruskal-Wallis 檢定結果呈現高度顯著（<span
class="math inline">\(\chi^2\)</span> = 50.057，p &lt;
0.001），拒絕五組最終效率中位數無顯著差異之虛無假設。</p>
<p>兩兩比較中，USR活動 - 就學 之調整後 p-value} 為 0.611（大於
0.05，未達顯著差異）。這代表在顯著水準 <span
class="math inline">\(\alpha\)</span> = 0.05下，就學與 USR
活動兩組在最終效率的分佈上仍然具備高度同質性</p>
<p>就醫在第一階段雖然效率較差，但在最終效率中，跟觀光組之比較呈現完全不顯著（p
= 0.611），代表兩者在最終效率上具備高度統計同質性。</p>
<p>就醫與購物也出現高度顯著（就醫 - 購物，p &lt;
0.001），在最終效率層面分類進中間</p>
<p>購物在最終效率上，則與其他目的出現高度顯著差異，因此判定，購物在最終效率上明顯地落後於其他所有目的</p>
<center>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">搭乘目的</th>
<th align="center">第一階段</th>
<th align="center">第二階段</th>
<th align="center">第三階段：最終綜合效率</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><strong>就學</strong></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
</tr>
<tr class="even">
<td align="center"><strong>USR活動</strong></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
</tr>
<tr class="odd">
<td align="center"><strong>觀光</strong></td>
<td align="center"><span
style="color:orange; font-weight:bold;">中</span></td>
<td align="center"><span
style="color:orange; font-weight:bold;">中</span></td>
<td align="center"><span
style="color:orange; font-weight:bold;">中</span></td>
</tr>
<tr class="even">
<td align="center"><strong>就醫</strong></td>
<td align="center"><span
style="color:red; font-weight:bold;">差</span></td>
<td align="center"><span
style="color:green; font-weight:bold;">優</span></td>
<td align="center"><span
style="color:orange; font-weight:bold;">中</span></td>
</tr>
<tr class="odd">
<td align="center"><strong>購物</strong></td>
<td align="center"><span
style="color:orange; font-weight:bold;">中</span></td>
<td align="center"><span
style="color:red; font-weight:bold;">差</span></td>
<td align="center"><span
style="color:red; font-weight:bold;">差</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="迴歸分析" class="section level2">
<h2>4.5 迴歸分析</h2>
<p>為探討各投入資源與環境變數對於效率值之邊際影響力，本研究進一步構建
Tobit 迴歸模型進行實證分析。</p>
<p>模型建構基於以下理由：</p>
<p>資料特性之限制：由於被解釋變數（營運效率、社福轉換效率及最終效率）均為
NDEA 模型計算所得之技術效率值，其數值範圍嚴格限制於 <span
class="math inline">\([0, 1]\)</span>
區間內。若採用一般最小平方法（OLS），我怕產生估計值超過合理界限或具備偏誤之情形，故採行
Tobit 模型以處理依變數之估計問題。</p>
<p>控制變數之引入：為釐清控制變數（搭乘目的）之影響力，模型自變數中引入五種搭乘目的作為虛擬變數），以『就學』為基準組（Reference
Group），藉此對比其他目的別在控制了各項資源投入（如：志工工時、補貼油資）後的效率差異。</p>
<p>參數估計方法：本模型採最大概似法（Maximum Likelihood Estimation,
MLE）進行參數估計，以確保在受限模型下估計係數之不偏性與有效性。</p>
<pre class="r"><code>library(VGAM)


QQ$grp &lt;- factor(QQ$grp)


# 模型 A：第一階段營運效率 Tobit 迴歸

cat(&quot;第一階段營運效率 迴歸結果\n&quot;)</code></pre>
<pre><code>第一階段營運效率 迴歸結果</code></pre>
<pre class="r"><code># 自變數對齊 QQ 欄位：VT, ST, OIL, STS 加上目的別開關 grp
tobit_S1E &lt;- vglm(S1E ~ VT + ST + OIL  + grp, 
                  tobit(Lower = 0, Upper = 1), data = QQ)
print(summary(tobit_S1E))</code></pre>
<pre><code>
Call:
vglm(formula = S1E ~ VT + ST + OIL + grp, family = tobit(Lower = 0, 
    Upper = 1), data = QQ)

Coefficients: 
                Estimate Std. Error    z value Pr(&gt;|z|)    
(Intercept):1  1.000e+00  3.700e-06 270278.907   &lt;2e-16 ***
(Intercept):2 -1.117e+01  7.435e-02   -150.236   &lt;2e-16 ***
VT             3.334e-03  4.300e-07   7752.750   &lt;2e-16 ***
ST             3.333e-03  2.154e-07  15478.612   &lt;2e-16 ***
OIL            3.333e-03  4.325e-07   7705.913   &lt;2e-16 ***
grpShop       -2.514e-06  6.040e-06     -0.416    0.677    
grpClinic      1.063e-05  6.814e-06      1.560    0.119    
grpTour       -4.082e-06  5.265e-06     -0.775    0.438    
grpUSR        -3.593e-06  4.848e-06     -0.741    0.459    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Names of linear predictors: mu, loglink(sd)

Log-likelihood: 811.8385 on 191 degrees of freedom

Number of Fisher scoring iterations: 7 </code></pre>
<pre class="r"><code># 模型 B：第二階段社會轉換效率Tobit 迴歸

cat(&quot;第二階段社會轉換效率 迴歸結果\n&quot;)</code></pre>
<pre><code>第二階段社會轉換效率 迴歸結果</code></pre>
<pre class="r"><code>tobit_S2E &lt;- vglm(S2E ~ STS + Money + SH + CO + grp, 
                  tobit(Lower = 0, Upper = 1), data = QQ)
print(summary(tobit_S2E))</code></pre>
<pre><code>
Call:
vglm(formula = S2E ~ STS + Money + SH + CO + grp, family = tobit(Lower = 0, 
    Upper = 1), data = QQ)

Coefficients: 
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1  9.867e-01  2.490e-02  39.632  &lt; 2e-16 ***
(Intercept):2 -2.315e+00  7.872e-02 -29.410  &lt; 2e-16 ***
STS            1.472e-02  1.597e-03   9.217  &lt; 2e-16 ***
Money          1.167e-03  8.873e-03   0.131   0.8954    
SH            -1.039e-03  1.323e-04  -7.848 4.21e-15 ***
CO            -6.195e-04  7.557e-05  -8.198 2.44e-16 ***
grpShop       -3.170e-02  5.413e-02  -0.586   0.5581    
grpClinic      3.860e-02  3.342e-02   1.155   0.2480    
grpTour       -7.243e-02  3.218e-02  -2.251   0.0244 *  
grpUSR        -4.209e-02  3.321e-02  -1.268   0.2050    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Names of linear predictors: mu, loglink(sd)

Log-likelihood: 50.9416 on 190 degrees of freedom

Number of Fisher scoring iterations: 8 </code></pre>
<pre class="r"><code># 模型 C：最終效率 Tobit 迴歸

cat(&quot;最終效率 迴歸結果\n&quot;)</code></pre>
<pre><code>最終效率 迴歸結果</code></pre>
<pre class="r"><code>tobit_FE &lt;- vglm(FE ~ VT + ST + OIL + STS + Money + SH + CO + grp, 
                 tobit(Lower = 0, Upper = 1), data = QQ)
print(summary(tobit_FE))</code></pre>
<pre><code>
Call:
vglm(formula = FE ~ VT + ST + OIL + STS + Money + SH + CO + grp, 
    family = tobit(Lower = 0, Upper = 1), data = QQ)

Coefficients: 
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1  9.886e-01  1.203e-02  82.206  &lt; 2e-16 ***
(Intercept):2 -3.052e+00  7.486e-02 -40.773  &lt; 2e-16 ***
VT             4.330e-03  1.445e-03   2.998 0.002720 ** 
ST             2.500e-03  7.548e-04   3.312 0.000926 ***
OIL            9.009e-05  1.451e-03   0.062 0.950482    
STS            6.918e-03  8.130e-04   8.510  &lt; 2e-16 ***
Money          6.734e-03  4.478e-03   1.504 0.132597    
SH            -6.156e-04  6.621e-05  -9.297  &lt; 2e-16 ***
CO            -4.488e-04  3.482e-05 -12.890  &lt; 2e-16 ***
grpShop        2.865e-02  2.778e-02   1.032 0.302273    
grpClinic      7.811e-02  2.356e-02   3.316 0.000914 ***
grpTour       -3.273e-03  1.733e-02  -0.189 0.850167    
grpUSR        -5.463e-03  1.609e-02  -0.340 0.734149    
---
Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1

Names of linear predictors: mu, loglink(sd)

Log-likelihood: 127.0156 on 187 degrees of freedom

Number of Fisher scoring iterations: 8 </code></pre>
</div>
<div id="finding-2" class="section level2">
<h2>Finding 2</h2>
<div id="第一階段-1" class="section level3">
<h3>第一階段</h3>
<p>應變數:第一階段純營運效率</p>
<p>自變數:志工時間（VT）、學生時間（ST）與油資補貼（OIL）</p>
<p>數據顯示，自變數對第一階段純營運效率均呈現顯著影響。</p>
<p>數值表現上，VT、ST 與 OIL 三者之邊際估計係數呈現高度相似</p>
<p>推測這三項實體投入成本將呈現固定比例之集體浪費，因此迴歸模型分攤了同等的影響。</p>
</div>
<div id="第二階段-1" class="section level3">
<h3>第二階段</h3>
<p>應變數:第二階段社會轉換效率</p>
<p>自變數:學生轉換社會價值投入時間(STS)
、總節省價值（Money）、活動收穫增加率（SH）與減碳量增加率（CO）</p>
<p>數據顯示，除了總節省價值，另外三個自變數對第二階段社會轉換效率均呈現顯著影響。</p>
<p>關於總節省價值之不顯著：
數據顯示節省價值對效率無統計顯著性，這反映出偏鄉共乘的時間與交通費節省，對於使用者的社會價值轉換並無明顯的邊際影響，這證實了社會轉換效率的關鍵在於活動體感(活動收穫)與環境效益(減碳量)，而非單純的時間費用節省。</p>
<p>觀光目的的結構劣勢：</p>
<p>在控制了自變數後，原本不顯著的觀光目的別虛擬變數（grpTour）轉化為顯著的負面影響。這項數據指出，即使在資源與產出完全相同的基準下，觀光車次的屬性，相較於就學等車次，在福利轉換上存在結構劣勢。</p>
</div>
<div id="最終效率-1" class="section level3">
<h3>最終效率</h3>
<p>應變數：最終效率</p>
<p>自變數：志工時間（VT）、學生時間（ST）、油資補貼（OIL）、學生轉換社會價值投入時間（STS）、總節省價值（Money）、活動收穫增加率（SH）與減碳量增加率（CO）</p>
<p>關於油資補貼與總節省價值之不顯著： 數據顯示，油資補貼（p =
0.950）與總節省價值（p =
0.132）皆未達統計顯著性。這反映出當共乘使用最終效率檢視時，這類型費用層面（油資消耗與費用節省），已不再是決定最終綜合效率高低的關鍵因素。</p>
<p>就醫目的的結構優勢:</p>
<p>控制了所有自變數後，原本前兩階段不顯著的就醫目的別（grpClinic）突然變得顯著（p
&lt; 0.001），而購物、觀光與 USR
則與基準組就學組在統計上無顯著差異。</p>
<p>這指出，在全面排除並控制了所有檯面上可量化的浪費與產出缺口後，就醫車次因為它獨特的結構，使其在最終效率上，比就學車次還要高出
0.078 分。根據數據推測就醫或許有隱形社會價值。</p>
</div>
</div>
<div id="管理與政策" class="section level2">
<h2>4.6 管理與政策</h2>
<div id="管理策略以目的為導向的調度優化" class="section level3">
<h3>管理策略:以「目的」為導向的調度優化</h3>
<p>需求優先調度給就學/就醫：針對就學與就醫行程，建立「優先排程機制」。利用模型中發現的結構優勢，與醫院或學校建立預約連動。</p>
<p>彈性需求集中化（購物/觀光）：數據顯示這兩類效率落後，應實施「時段限定服務」或「強制共乘」，利用「預約併單」提高車輛載客率，解決箱形圖中看到的離群值偏大問題。</p>
</div>
<div id="政策規劃" class="section level3">
<h3>政策規劃:</h3>
<div id="section" class="section level4">
<h4>1</h4>
<p>根據迴歸模型結果，在排除並控制了所有的資源投入（如工時、補貼）與產出限制後，『就醫』目的別呈現顯著的正向係數（<span
class="math inline">\(+0.078\)</span>）。此結果揭示了就醫車次具備優於其他目的的結構性績效優勢，這意味著該類需求不僅是偏鄉交通的剛需，且在社會效益轉化上具備更高的效益轉換能力。因此建議將就醫需求由單純的運輸服務對象，轉型為高社會價值的優先需求。政策方針應從過去的『均等資源分配』轉向『價值優先導向』，賦予醫療相關車次更高的調度優先權與補助。</p>
</div>
<div id="section-1" class="section level4">
<h4>2</h4>
<p>重構偏鄉交通之資源分配邏輯：當前資源分配過度依賴油資與補貼與金錢節省等顯性財務指標，然而實證結果證實這些指標在最終績效中已不具顯著性。政府應改善均等化資源分配，轉而推動價值優先導向的預算編列。</p>
<p>所謂的價值優先導向，就是將我們在模型中的社會轉換係數納入預算編列的公式。未來，每一塊錢的補貼，都應包含對投入時間、活動收穫與減碳效益的評估。這不僅能減少補貼無效的均等化分配，更能引導共乘資源投入到真正能改變偏鄉結構的關鍵節點上</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
